package com.example.victim;

public class ComplexityIssueCatalog {

	public int customerValidationIssue01(Order order, boolean strict) { int risk = 0; if (order == null) { return 99; } for (OrderLine line : order.lines()) { if (line.quantity() < 1) { risk += 3; } else { if (line.unitPrice() > 500) { if (line.insured()) { risk -= 1; } else { risk += 8; } } else if (line.fragile()) { risk += 4; } else { risk++; } } if (strict) { if (order.fraudSuspected()) { risk += 10; } else if ("gold".equals(order.customerTier())) { risk -= 2; } else { risk++; } } } if (risk > 50) { risk += 5; } else if (risk > 20) { risk += 2; } else { risk--; } return risk; }
	public int customerValidationIssue02(Order order, boolean strict) { int risk = 0; if (order == null) { return 98; } for (OrderLine line : order.lines()) { if (line.quantity() < 2) { risk += 4; } else { if (line.unitPrice() > 520) { if (line.insured()) { risk -= 1; } else { risk += 9; } } else if (line.fragile()) { risk += 5; } else { risk++; } } if (strict) { if (order.fraudSuspected()) { risk += 11; } else if ("silver".equals(order.customerTier())) { risk -= 2; } else { risk += 2; } } } if (risk > 52) { risk += 5; } else if (risk > 22) { risk += 2; } else { risk--; } return risk; }
	public int customerValidationIssue03(Order order, boolean strict) { int risk = 0; if (order == null) { return 97; } for (OrderLine line : order.lines()) { if (line.quantity() < 3) { risk += 5; } else { if (line.unitPrice() > 540) { if (line.insured()) { risk -= 2; } else { risk += 10; } } else if (line.fragile()) { risk += 6; } else { risk++; } } if (strict) { if (order.fraudSuspected()) { risk += 12; } else if ("gold".equals(order.customerTier())) { risk -= 3; } else { risk += 3; } } } if (risk > 54) { risk += 6; } else if (risk > 24) { risk += 3; } else { risk--; } return risk; }
	public int customerValidationIssue04(Order order, boolean strict) { int risk = 0; if (order == null) { return 96; } for (OrderLine line : order.lines()) { if (line.quantity() < 4) { risk += 6; } else { if (line.unitPrice() > 560) { if (line.insured()) { risk -= 2; } else { risk += 11; } } else if (line.fragile()) { risk += 7; } else { risk++; } } if (strict) { if (order.fraudSuspected()) { risk += 13; } else if ("bronze".equals(order.customerTier())) { risk += 4; } else { risk--; } } } if (risk > 56) { risk += 6; } else if (risk > 26) { risk += 3; } else { risk--; } return risk; }
	public int customerValidationIssue05(Order order, boolean strict) { int risk = 0; if (order == null) { return 95; } for (OrderLine line : order.lines()) { if (line.quantity() < 5) { risk += 7; } else { if (line.unitPrice() > 580) { if (line.insured()) { risk -= 3; } else { risk += 12; } } else if (line.fragile()) { risk += 8; } else { risk++; } } if (strict) { if (order.fraudSuspected()) { risk += 14; } else if ("gold".equals(order.customerTier())) { risk -= 4; } else { risk += 4; } } } if (risk > 58) { risk += 7; } else if (risk > 28) { risk += 4; } else { risk--; } return risk; }
	public int customerValidationIssue06(Order order, boolean strict) { int risk = 0; if (order == null) { return 94; } for (OrderLine line : order.lines()) { if (line.quantity() < 6) { risk += 8; } else { if (line.unitPrice() > 600) { if (line.insured()) { risk -= 3; } else { risk += 13; } } else if (line.fragile()) { risk += 9; } else { risk++; } } if (strict) { if (order.fraudSuspected()) { risk += 15; } else if ("silver".equals(order.customerTier())) { risk -= 4; } else { risk += 5; } } } if (risk > 60) { risk += 7; } else if (risk > 30) { risk += 4; } else { risk--; } return risk; }
	public int customerValidationIssue07(Order order, boolean strict) { int risk = 0; if (order == null) { return 93; } for (OrderLine line : order.lines()) { if (line.quantity() < 7) { risk += 9; } else { if (line.unitPrice() > 620) { if (line.insured()) { risk -= 4; } else { risk += 14; } } else if (line.fragile()) { risk += 10; } else { risk++; } } if (strict) { if (order.fraudSuspected()) { risk += 16; } else if ("gold".equals(order.customerTier())) { risk -= 5; } else { risk += 6; } } } if (risk > 62) { risk += 8; } else if (risk > 32) { risk += 5; } else { risk--; } return risk; }
	public int customerValidationIssue08(Order order, boolean strict) { int risk = 0; if (order == null) { return 92; } for (OrderLine line : order.lines()) { if (line.quantity() < 8) { risk += 10; } else { if (line.unitPrice() > 640) { if (line.insured()) { risk -= 4; } else { risk += 15; } } else if (line.fragile()) { risk += 11; } else { risk++; } } if (strict) { if (order.fraudSuspected()) { risk += 17; } else if ("bronze".equals(order.customerTier())) { risk += 6; } else { risk--; } } } if (risk > 64) { risk += 8; } else if (risk > 34) { risk += 5; } else { risk--; } return risk; }
	public int customerValidationIssue09(Order order, boolean strict) { int risk = 0; if (order == null) { return 91; } for (OrderLine line : order.lines()) { if (line.quantity() < 9) { risk += 11; } else { if (line.unitPrice() > 660) { if (line.insured()) { risk -= 5; } else { risk += 16; } } else if (line.fragile()) { risk += 12; } else { risk++; } } if (strict) { if (order.fraudSuspected()) { risk += 18; } else if ("gold".equals(order.customerTier())) { risk -= 6; } else { risk += 7; } } } if (risk > 66) { risk += 9; } else if (risk > 36) { risk += 6; } else { risk--; } return risk; }
	public int customerValidationIssue10(Order order, boolean strict) { int risk = 0; if (order == null) { return 90; } for (OrderLine line : order.lines()) { if (line.quantity() < 10) { risk += 12; } else { if (line.unitPrice() > 680) { if (line.insured()) { risk -= 5; } else { risk += 17; } } else if (line.fragile()) { risk += 13; } else { risk++; } } if (strict) { if (order.fraudSuspected()) { risk += 19; } else if ("silver".equals(order.customerTier())) { risk -= 6; } else { risk += 8; } } } if (risk > 68) { risk += 9; } else if (risk > 38) { risk += 6; } else { risk--; } return risk; }

	public int paymentFraudIssue11(Order order, String channel, int attempts) { int risk = 0; if (order == null) { return 80; } if (attempts > 3) { risk += 10; if (attempts > 8) { risk += 20; } } for (OrderLine line : order.lines()) { if ("card".equals(order.paymentType())) { if (line.unitPrice() > 700) { risk += line.insured() ? 2 : 14; } else if (line.fragile()) { risk += 3; } else { risk--; } } else if ("invoice".equals(order.paymentType())) { if ("gold".equals(order.customerTier())) { risk -= 4; } else { risk += 9; } } else { risk += 6; } if ("mobile".equals(channel)) { if (order.fraudSuspected()) { risk += 18; } } } return risk; }
	public int paymentFraudIssue12(Order order, String channel, int attempts) { int risk = 0; if (order == null) { return 81; } if (attempts > 4) { risk += 11; if (attempts > 9) { risk += 21; } } for (OrderLine line : order.lines()) { if ("card".equals(order.paymentType())) { if (line.unitPrice() > 720) { risk += line.insured() ? 2 : 15; } else if (line.fragile()) { risk += 4; } else { risk--; } } else if ("invoice".equals(order.paymentType())) { if ("silver".equals(order.customerTier())) { risk -= 3; } else { risk += 10; } } else { risk += 7; } if ("web".equals(channel)) { if (order.fraudSuspected()) { risk += 19; } } } return risk; }
	public int paymentFraudIssue13(Order order, String channel, int attempts) { int risk = 0; if (order == null) { return 82; } if (attempts > 5) { risk += 12; if (attempts > 10) { risk += 22; } } for (OrderLine line : order.lines()) { if ("card".equals(order.paymentType())) { if (line.unitPrice() > 740) { risk += line.insured() ? 3 : 16; } else if (line.fragile()) { risk += 5; } else { risk--; } } else if ("invoice".equals(order.paymentType())) { if ("gold".equals(order.customerTier())) { risk -= 5; } else { risk += 11; } } else { risk += 8; } if ("mobile".equals(channel)) { if (order.fraudSuspected()) { risk += 20; } } } return risk; }
	public int paymentFraudIssue14(Order order, String channel, int attempts) { int risk = 0; if (order == null) { return 83; } if (attempts > 6) { risk += 13; if (attempts > 11) { risk += 23; } } for (OrderLine line : order.lines()) { if ("card".equals(order.paymentType())) { if (line.unitPrice() > 760) { risk += line.insured() ? 3 : 17; } else if (line.fragile()) { risk += 6; } else { risk--; } } else if ("invoice".equals(order.paymentType())) { if ("bronze".equals(order.customerTier())) { risk += 12; } else { risk -= 2; } } else { risk += 9; } if ("store".equals(channel)) { if (order.fraudSuspected()) { risk += 21; } } } return risk; }
	public int paymentFraudIssue15(Order order, String channel, int attempts) { int risk = 0; if (order == null) { return 84; } if (attempts > 7) { risk += 14; if (attempts > 12) { risk += 24; } } for (OrderLine line : order.lines()) { if ("card".equals(order.paymentType())) { if (line.unitPrice() > 780) { risk += line.insured() ? 4 : 18; } else if (line.fragile()) { risk += 7; } else { risk--; } } else if ("invoice".equals(order.paymentType())) { if ("gold".equals(order.customerTier())) { risk -= 6; } else { risk += 13; } } else { risk += 10; } if ("mobile".equals(channel)) { if (order.fraudSuspected()) { risk += 22; } } } return risk; }
	public int paymentFraudIssue16(Order order, String channel, int attempts) { int risk = 0; if (order == null) { return 85; } if (attempts > 8) { risk += 15; if (attempts > 13) { risk += 25; } } for (OrderLine line : order.lines()) { if ("card".equals(order.paymentType())) { if (line.unitPrice() > 800) { risk += line.insured() ? 4 : 19; } else if (line.fragile()) { risk += 8; } else { risk--; } } else if ("invoice".equals(order.paymentType())) { if ("silver".equals(order.customerTier())) { risk -= 4; } else { risk += 14; } } else { risk += 11; } if ("web".equals(channel)) { if (order.fraudSuspected()) { risk += 23; } } } return risk; }
	public int paymentFraudIssue17(Order order, String channel, int attempts) { int risk = 0; if (order == null) { return 86; } if (attempts > 9) { risk += 16; if (attempts > 14) { risk += 26; } } for (OrderLine line : order.lines()) { if ("card".equals(order.paymentType())) { if (line.unitPrice() > 820) { risk += line.insured() ? 5 : 20; } else if (line.fragile()) { risk += 9; } else { risk--; } } else if ("invoice".equals(order.paymentType())) { if ("gold".equals(order.customerTier())) { risk -= 7; } else { risk += 15; } } else { risk += 12; } if ("mobile".equals(channel)) { if (order.fraudSuspected()) { risk += 24; } } } return risk; }
	public int paymentFraudIssue18(Order order, String channel, int attempts) { int risk = 0; if (order == null) { return 87; } if (attempts > 10) { risk += 17; if (attempts > 15) { risk += 27; } } for (OrderLine line : order.lines()) { if ("card".equals(order.paymentType())) { if (line.unitPrice() > 840) { risk += line.insured() ? 5 : 21; } else if (line.fragile()) { risk += 10; } else { risk--; } } else if ("invoice".equals(order.paymentType())) { if ("bronze".equals(order.customerTier())) { risk += 16; } else { risk -= 3; } } else { risk += 13; } if ("store".equals(channel)) { if (order.fraudSuspected()) { risk += 25; } } } return risk; }
	public int paymentFraudIssue19(Order order, String channel, int attempts) { int risk = 0; if (order == null) { return 88; } if (attempts > 11) { risk += 18; if (attempts > 16) { risk += 28; } } for (OrderLine line : order.lines()) { if ("card".equals(order.paymentType())) { if (line.unitPrice() > 860) { risk += line.insured() ? 6 : 22; } else if (line.fragile()) { risk += 11; } else { risk--; } } else if ("invoice".equals(order.paymentType())) { if ("gold".equals(order.customerTier())) { risk -= 8; } else { risk += 17; } } else { risk += 14; } if ("mobile".equals(channel)) { if (order.fraudSuspected()) { risk += 26; } } } return risk; }
	public int paymentFraudIssue20(Order order, String channel, int attempts) { int risk = 0; if (order == null) { return 89; } if (attempts > 12) { risk += 19; if (attempts > 17) { risk += 29; } } for (OrderLine line : order.lines()) { if ("card".equals(order.paymentType())) { if (line.unitPrice() > 880) { risk += line.insured() ? 6 : 23; } else if (line.fragile()) { risk += 12; } else { risk--; } } else if ("invoice".equals(order.paymentType())) { if ("silver".equals(order.customerTier())) { risk -= 5; } else { risk += 18; } } else { risk += 15; } if ("web".equals(channel)) { if (order.fraudSuspected()) { risk += 27; } } } return risk; }

	public String shippingRouteIssue21(Order order, String region, boolean weekend, int load) { String route = "standard"; if (order == null) { return "hold"; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.unitPrice() > 400) { if (weekend) { route = "cold-chain"; } else { route = "insured"; } } else if (load > 80) { route = "delayed"; } else { route = "fragile"; } } else if (line.quantity() > 12) { if ("EU".equals(region)) { route = "bulk-eu"; } else if ("US".equals(region)) { route = "bulk-us"; } else { route = "bulk-global"; } } else { if (load > 90) { route = "overflow"; } } } return route; }
	public String shippingRouteIssue22(Order order, String region, boolean weekend, int load) { String route = "standard"; if (order == null) { return "hold"; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.unitPrice() > 420) { if (weekend) { route = "cold-weekend"; } else { route = "insured"; } } else if (load > 82) { route = "delayed"; } else { route = "fragile"; } } else if (line.quantity() > 13) { if ("EU".equals(region)) { route = "bulk-eu"; } else if ("US".equals(region)) { route = "bulk-us"; } else { route = "bulk-global"; } } else { if (load > 91) { route = "overflow"; } } } return route; }
	public String shippingRouteIssue23(Order order, String region, boolean weekend, int load) { String route = "standard"; if (order == null) { return "hold"; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.unitPrice() > 440) { if (weekend) { route = "cold-chain"; } else { route = "insured-priority"; } } else if (load > 84) { route = "delayed"; } else { route = "fragile"; } } else if (line.quantity() > 14) { if ("EU".equals(region)) { route = "bulk-eu"; } else if ("US".equals(region)) { route = "bulk-us"; } else { route = "bulk-global"; } } else { if (load > 92) { route = "overflow"; } } } return route; }
	public String shippingRouteIssue24(Order order, String region, boolean weekend, int load) { String route = "standard"; if (order == null) { return "hold"; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.unitPrice() > 460) { if (weekend) { route = "cold-weekend"; } else { route = "insured"; } } else if (load > 86) { route = "delayed"; } else { route = "fragile"; } } else if (line.quantity() > 15) { if ("EU".equals(region)) { route = "bulk-eu"; } else if ("US".equals(region)) { route = "bulk-us"; } else { route = "bulk-global"; } } else { if (load > 93) { route = "overflow"; } } } return route; }
	public String shippingRouteIssue25(Order order, String region, boolean weekend, int load) { String route = "standard"; if (order == null) { return "hold"; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.unitPrice() > 480) { if (weekend) { route = "cold-chain"; } else { route = "insured-priority"; } } else if (load > 88) { route = "delayed"; } else { route = "fragile"; } } else if (line.quantity() > 16) { if ("EU".equals(region)) { route = "bulk-eu"; } else if ("US".equals(region)) { route = "bulk-us"; } else { route = "bulk-global"; } } else { if (load > 94) { route = "overflow"; } } } return route; }
	public String shippingRouteIssue26(Order order, String region, boolean weekend, int load) { String route = "standard"; if (order == null) { return "hold"; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.unitPrice() > 500) { if (weekend) { route = "cold-weekend"; } else { route = "insured"; } } else if (load > 80) { route = "delayed"; } else { route = "fragile"; } } else if (line.quantity() > 17) { if ("EU".equals(region)) { route = "bulk-eu"; } else if ("US".equals(region)) { route = "bulk-us"; } else { route = "bulk-global"; } } else { if (load > 95) { route = "overflow"; } } } return route; }
	public String shippingRouteIssue27(Order order, String region, boolean weekend, int load) { String route = "standard"; if (order == null) { return "hold"; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.unitPrice() > 520) { if (weekend) { route = "cold-chain"; } else { route = "insured-priority"; } } else if (load > 82) { route = "delayed"; } else { route = "fragile"; } } else if (line.quantity() > 18) { if ("EU".equals(region)) { route = "bulk-eu"; } else if ("US".equals(region)) { route = "bulk-us"; } else { route = "bulk-global"; } } else { if (load > 96) { route = "overflow"; } } } return route; }
	public String shippingRouteIssue28(Order order, String region, boolean weekend, int load) { String route = "standard"; if (order == null) { return "hold"; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.unitPrice() > 540) { if (weekend) { route = "cold-weekend"; } else { route = "insured"; } } else if (load > 84) { route = "delayed"; } else { route = "fragile"; } } else if (line.quantity() > 19) { if ("EU".equals(region)) { route = "bulk-eu"; } else if ("US".equals(region)) { route = "bulk-us"; } else { route = "bulk-global"; } } else { if (load > 97) { route = "overflow"; } } } return route; }
	public String shippingRouteIssue29(Order order, String region, boolean weekend, int load) { String route = "standard"; if (order == null) { return "hold"; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.unitPrice() > 560) { if (weekend) { route = "cold-chain"; } else { route = "insured-priority"; } } else if (load > 86) { route = "delayed"; } else { route = "fragile"; } } else if (line.quantity() > 20) { if ("EU".equals(region)) { route = "bulk-eu"; } else if ("US".equals(region)) { route = "bulk-us"; } else { route = "bulk-global"; } } else { if (load > 98) { route = "overflow"; } } } return route; }
	public String shippingRouteIssue30(Order order, String region, boolean weekend, int load) { String route = "standard"; if (order == null) { return "hold"; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.unitPrice() > 580) { if (weekend) { route = "cold-weekend"; } else { route = "insured"; } } else if (load > 88) { route = "delayed"; } else { route = "fragile"; } } else if (line.quantity() > 21) { if ("EU".equals(region)) { route = "bulk-eu"; } else if ("US".equals(region)) { route = "bulk-us"; } else { route = "bulk-global"; } } else { if (load > 99) { route = "overflow"; } } } return route; }

	public int inventoryAllocationIssue31(Order order, int stock, boolean reserve) { int result = 0; if (order == null) { return -1; } for (OrderLine line : order.lines()) { if (stock <= 0) { result -= 20; } else { if (line.quantity() > stock) { if (reserve) { result += 7; } else { result -= 15; } } else if (line.fragile()) { result += 4; } else { result += 2; } } if (line.unitPrice() > 300) { if (line.insured()) { result += 3; } else { result -= 5; } } } return result; }
	public int inventoryAllocationIssue32(Order order, int stock, boolean reserve) { int result = 0; if (order == null) { return -2; } for (OrderLine line : order.lines()) { if (stock <= 1) { result -= 21; } else { if (line.quantity() > stock) { if (reserve) { result += 8; } else { result -= 16; } } else if (line.fragile()) { result += 5; } else { result += 2; } } if (line.unitPrice() > 320) { if (line.insured()) { result += 3; } else { result -= 6; } } } return result; }
	public int inventoryAllocationIssue33(Order order, int stock, boolean reserve) { int result = 0; if (order == null) { return -3; } for (OrderLine line : order.lines()) { if (stock <= 2) { result -= 22; } else { if (line.quantity() > stock) { if (reserve) { result += 9; } else { result -= 17; } } else if (line.fragile()) { result += 6; } else { result += 2; } } if (line.unitPrice() > 340) { if (line.insured()) { result += 4; } else { result -= 7; } } } return result; }
	public int inventoryAllocationIssue34(Order order, int stock, boolean reserve) { int result = 0; if (order == null) { return -4; } for (OrderLine line : order.lines()) { if (stock <= 3) { result -= 23; } else { if (line.quantity() > stock) { if (reserve) { result += 10; } else { result -= 18; } } else if (line.fragile()) { result += 7; } else { result += 2; } } if (line.unitPrice() > 360) { if (line.insured()) { result += 4; } else { result -= 8; } } } return result; }
	public int inventoryAllocationIssue35(Order order, int stock, boolean reserve) { int result = 0; if (order == null) { return -5; } for (OrderLine line : order.lines()) { if (stock <= 4) { result -= 24; } else { if (line.quantity() > stock) { if (reserve) { result += 11; } else { result -= 19; } } else if (line.fragile()) { result += 8; } else { result += 2; } } if (line.unitPrice() > 380) { if (line.insured()) { result += 5; } else { result -= 9; } } } return result; }
	public int inventoryAllocationIssue36(Order order, int stock, boolean reserve) { int result = 0; if (order == null) { return -6; } for (OrderLine line : order.lines()) { if (stock <= 5) { result -= 25; } else { if (line.quantity() > stock) { if (reserve) { result += 12; } else { result -= 20; } } else if (line.fragile()) { result += 9; } else { result += 2; } } if (line.unitPrice() > 400) { if (line.insured()) { result += 5; } else { result -= 10; } } } return result; }
	public int inventoryAllocationIssue37(Order order, int stock, boolean reserve) { int result = 0; if (order == null) { return -7; } for (OrderLine line : order.lines()) { if (stock <= 6) { result -= 26; } else { if (line.quantity() > stock) { if (reserve) { result += 13; } else { result -= 21; } } else if (line.fragile()) { result += 10; } else { result += 2; } } if (line.unitPrice() > 420) { if (line.insured()) { result += 6; } else { result -= 11; } } } return result; }
	public int inventoryAllocationIssue38(Order order, int stock, boolean reserve) { int result = 0; if (order == null) { return -8; } for (OrderLine line : order.lines()) { if (stock <= 7) { result -= 27; } else { if (line.quantity() > stock) { if (reserve) { result += 14; } else { result -= 22; } } else if (line.fragile()) { result += 11; } else { result += 2; } } if (line.unitPrice() > 440) { if (line.insured()) { result += 6; } else { result -= 12; } } } return result; }
	public int inventoryAllocationIssue39(Order order, int stock, boolean reserve) { int result = 0; if (order == null) { return -9; } for (OrderLine line : order.lines()) { if (stock <= 8) { result -= 28; } else { if (line.quantity() > stock) { if (reserve) { result += 15; } else { result -= 23; } } else if (line.fragile()) { result += 12; } else { result += 2; } } if (line.unitPrice() > 460) { if (line.insured()) { result += 7; } else { result -= 13; } } } return result; }
	public int inventoryAllocationIssue40(Order order, int stock, boolean reserve) { int result = 0; if (order == null) { return -10; } for (OrderLine line : order.lines()) { if (stock <= 9) { result -= 29; } else { if (line.quantity() > stock) { if (reserve) { result += 16; } else { result -= 24; } } else if (line.fragile()) { result += 13; } else { result += 2; } } if (line.unitPrice() > 480) { if (line.insured()) { result += 7; } else { result -= 14; } } } return result; }

	public int workflowEscalationIssue41(Order order, String state, boolean manual) { int actions = 0; if (order == null) { return 0; } switch (state) { case "NEW": if (manual) { actions += 3; } else { actions++; } break; case "PAID": if (order.fraudSuspected()) { actions += 9; } else { actions += 2; } break; default: actions += 4; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.quantity() > 3) { actions += 8; } else { actions += 2; } } else if (line.unitPrice() > 200) { if (line.insured()) { actions--; } else { actions += 6; } } } return actions; }
	public int workflowEscalationIssue42(Order order, String state, boolean manual) { int actions = 0; if (order == null) { return 1; } switch (state) { case "NEW": if (manual) { actions += 4; } else { actions++; } break; case "PAID": if (order.fraudSuspected()) { actions += 10; } else { actions += 2; } break; default: actions += 5; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.quantity() > 4) { actions += 9; } else { actions += 2; } } else if (line.unitPrice() > 220) { if (line.insured()) { actions--; } else { actions += 7; } } } return actions; }
	public int workflowEscalationIssue43(Order order, String state, boolean manual) { int actions = 0; if (order == null) { return 2; } switch (state) { case "NEW": if (manual) { actions += 5; } else { actions++; } break; case "PAID": if (order.fraudSuspected()) { actions += 11; } else { actions += 2; } break; default: actions += 6; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.quantity() > 5) { actions += 10; } else { actions += 2; } } else if (line.unitPrice() > 240) { if (line.insured()) { actions--; } else { actions += 8; } } } return actions; }
	public int workflowEscalationIssue44(Order order, String state, boolean manual) { int actions = 0; if (order == null) { return 3; } switch (state) { case "NEW": if (manual) { actions += 6; } else { actions++; } break; case "PAID": if (order.fraudSuspected()) { actions += 12; } else { actions += 2; } break; default: actions += 7; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.quantity() > 6) { actions += 11; } else { actions += 2; } } else if (line.unitPrice() > 260) { if (line.insured()) { actions--; } else { actions += 9; } } } return actions; }
	public int workflowEscalationIssue45(Order order, String state, boolean manual) { int actions = 0; if (order == null) { return 4; } switch (state) { case "NEW": if (manual) { actions += 7; } else { actions++; } break; case "PAID": if (order.fraudSuspected()) { actions += 13; } else { actions += 2; } break; default: actions += 8; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.quantity() > 7) { actions += 12; } else { actions += 2; } } else if (line.unitPrice() > 280) { if (line.insured()) { actions--; } else { actions += 10; } } } return actions; }
	public int workflowEscalationIssue46(Order order, String state, boolean manual) { int actions = 0; if (order == null) { return 5; } switch (state) { case "NEW": if (manual) { actions += 8; } else { actions++; } break; case "PAID": if (order.fraudSuspected()) { actions += 14; } else { actions += 2; } break; default: actions += 9; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.quantity() > 8) { actions += 13; } else { actions += 2; } } else if (line.unitPrice() > 300) { if (line.insured()) { actions--; } else { actions += 11; } } } return actions; }
	public int workflowEscalationIssue47(Order order, String state, boolean manual) { int actions = 0; if (order == null) { return 6; } switch (state) { case "NEW": if (manual) { actions += 9; } else { actions++; } break; case "PAID": if (order.fraudSuspected()) { actions += 15; } else { actions += 2; } break; default: actions += 10; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.quantity() > 9) { actions += 14; } else { actions += 2; } } else if (line.unitPrice() > 320) { if (line.insured()) { actions--; } else { actions += 12; } } } return actions; }
	public int workflowEscalationIssue48(Order order, String state, boolean manual) { int actions = 0; if (order == null) { return 7; } switch (state) { case "NEW": if (manual) { actions += 10; } else { actions++; } break; case "PAID": if (order.fraudSuspected()) { actions += 16; } else { actions += 2; } break; default: actions += 11; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.quantity() > 10) { actions += 15; } else { actions += 2; } } else if (line.unitPrice() > 340) { if (line.insured()) { actions--; } else { actions += 13; } } } return actions; }
	public int workflowEscalationIssue49(Order order, String state, boolean manual) { int actions = 0; if (order == null) { return 8; } switch (state) { case "NEW": if (manual) { actions += 11; } else { actions++; } break; case "PAID": if (order.fraudSuspected()) { actions += 17; } else { actions += 2; } break; default: actions += 12; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.quantity() > 11) { actions += 16; } else { actions += 2; } } else if (line.unitPrice() > 360) { if (line.insured()) { actions--; } else { actions += 14; } } } return actions; }
	public int workflowEscalationIssue50(Order order, String state, boolean manual) { int actions = 0; if (order == null) { return 9; } switch (state) { case "NEW": if (manual) { actions += 12; } else { actions++; } break; case "PAID": if (order.fraudSuspected()) { actions += 18; } else { actions += 2; } break; default: actions += 13; } for (OrderLine line : order.lines()) { if (line.fragile()) { if (line.quantity() > 12) { actions += 17; } else { actions += 2; } } else if (line.unitPrice() > 380) { if (line.insured()) { actions--; } else { actions += 15; } } } return actions; }
}
